name: Tests (End-to-End)

on:
  push:
    branches:
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  cypress:
    name: Cypress E2E
    runs-on: [self-hosted, svc]
    continue-on-error: true
    strategy:
      matrix:
        node-version: [16]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
