name: Tests (End-to-End)

on:
  push:
    branches:
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn build && yarn start
